export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
]

export const INDIAN_UNION_TERRITORIES = [
  "Delhi",
  "Puducherry",
  "Jammu and Kashmir",
  "Ladakh",
  "Chandigarh",
  "Andaman and Nicobar Islands",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
]

export const CURRENT_CM_BY_REGION: Record<string, { name: string; wikiTitle: string } | null> = {
  // States (as-of mid‑2024)
  "Andhra Pradesh": { name: "N. Chandrababu Naidu", wikiTitle: "N._Chandrababu_Naidu" },
  "Arunachal Pradesh": { name: "Pema Khandu", wikiTitle: "Pema_Khandu" },
  Assam: { name: "Himanta Biswa Sarma", wikiTitle: "Himanta_Biswa_Sarma" },
  Bihar: { name: "Nitish Kumar", wikiTitle: "Nitish_Kumar" },
  Chhattisgarh: { name: "Vishnu Deo Sai", wikiTitle: "Vishnu_Deo_Sai" },
  Goa: { name: "Pramod Sawant", wikiTitle: "Pramod_Sawant" },
  Gujarat: { name: "Bhupendrabhai Patel", wikiTitle: "Bhupendrabhai_Patel" },
  Haryana: { name: "Nayab Singh Saini", wikiTitle: "Nayab_Singh_Saini" },
  "Himachal Pradesh": { name: "Sukhvinder Singh Sukhu", wikiTitle: "Sukhvinder_Singh_Sukhu" },
  Jharkhand: { name: "Champai Soren", wikiTitle: "Champai_Soren" },
  Karnataka: { name: "Siddaramaiah", wikiTitle: "Siddaramaiah" },
  Kerala: { name: "Pinarayi Vijayan", wikiTitle: "Pinarayi_Vijayan" },
  "Madhya Pradesh": { name: "Mohan Yadav", wikiTitle: "Mohan_Yadav" },
  Maharashtra: { name: "Eknath Shinde", wikiTitle: "Eknath_Shinde" },
  Manipur: { name: "N. Biren Singh", wikiTitle: "N._Biren_Singh" },
  Meghalaya: { name: "Conrad Sangma", wikiTitle: "Conrad_Sangma" },
  Mizoram: { name: "Lalduhoma", wikiTitle: "Lalduhoma" },
  Nagaland: { name: "Neiphiu Rio", wikiTitle: "Neiphiu_Rio" },
  Odisha: { name: "Mohan Charan Majhi", wikiTitle: "Mohan_Charan_Majhi" },
  Punjab: { name: "Bhagwant Mann", wikiTitle: "Bhagwant_Mann" },
  Rajasthan: { name: "Bhajan Lal Sharma", wikiTitle: "Bhajan_Lal_Sharma" },
  Sikkim: { name: "Prem Singh Tamang", wikiTitle: "Prem_Singh_Tamang" },
  "Tamil Nadu": { name: "M. K. Stalin", wikiTitle: "M._K._Stalin" },
  Telangana: { name: "Revanth Reddy", wikiTitle: "Revanth_Reddy" },
  Tripura: { name: "Manik Saha", wikiTitle: "Manik_Saha" },
  "Uttar Pradesh": { name: "Yogi Adityanath", wikiTitle: "Yogi_Adityanath" },
  Uttarakhand: { name: "Pushkar Singh Dhami", wikiTitle: "Pushkar_Singh_Dhami" },
  "West Bengal": { name: "Mamata Banerjee", wikiTitle: "Mamata_Banerjee" },

  // Union Territories
  Delhi: { name: "Arvind Kejriwal", wikiTitle: "Arvind_Kejriwal" },
  Puducherry: { name: "N. Rangaswamy", wikiTitle: "N._Rangaswamy" },

  // UTs with no CM currently
  "Jammu and Kashmir": null,
  Ladakh: null,
  Chandigarh: null,
  "Andaman and Nicobar Islands": null,
  "Dadra and Nagar Haveli and Daman and Diu": null,
  Lakshadweep: null,
}
